### ISSUE TITLE
Cucumber Tables not printed in the output

### ISSUE THREAD

**Issue by si-mikey** [webdriverio/wdio-spec-reporter#14]
The below screenshots is that of a step that contains a table and the data in that table is not displayed to the user. 
![screen shot 2016-10-28 at 12 35 54 pm](https://cloud.githubusercontent.com/assets/1561914/19814436/2b71da1a-9d0c-11e6-8d81-6942f2a2348f.png)

**Comment by philipbeadle** [comment]
I really need to get hold of the extyra text under the Feature and Scenario titles, how can I do that?

Feature: Getting around the store
    **People have lots of ways to navigate your store so we need to make sure the different ways such as typing and
    address or selecting a historical link all work.**

    @phil
    Scenario: Open a browser and select the Ladies Outerwear address in your history
        **Add some text here.**
        * Open the app at "/list/ladies_outerwear"
        * The title is "SHOP"
        * You will see a header for "Ladies Outerwear"

**Comment by christian-bromann** [comment]
This needs to be propagated by the cucumber framework adapter first before get hold of this. I don't think cucumber provides that data.
