### ISSUE TITLE
Please upload wdio-spec-reporter to npm

### ISSUE THREAD

**Issue by leutloff** [webdriverio/wdio-spec-reporter#3]
Running wdio with option 
{ reporters: ['spec'] } 
instead of 'dot' in wdio.conf.js fails with this error:
Error: reporter "wdio-spec-reporter" is not installed. Error: Error: Cannot find module 'wdio-spec-reporter'

But the wdio-spec-reporter is not available from npm. 

I have not tried to use it from git directly, sofar. I assume that the deferred upload is intentional.

These are the used packages:
  "devDependencies": {
    "chai": "^3.5.0",
    "mocha": "^2.4.5",
    "selenium-standalone": "^5.1.0",
    "util": "^0.10.3",
    "wdio-junit-reporter": "0.0.2",
    "wdio-mocha-framework": "^0.2.12",
    "wdio-selenium-standalone-service": "0.0.1",
    "webdriverio": "^4.0.5"
  },

I have prepared a build on Travis CI. In the beginning you see the working case with 'dot' and the in the last line the failing case with 'spec'. I do not want the build itself fail so I ored the failures...

In line 500 of this build the error message is shown:
[https://travis-ci.org/leutloff/e2e-webdriverio-mocha-tdd-example/builds/120160625](https://travis-ci.org/leutloff/e2e-webdriverio-mocha-tdd-example/builds/120160625)

**Comment by zckrs** [comment]
:+1:  should be publish on NPM

**Comment by jbhelfrich** [comment]
As of 60 seconds ago:
`$ npm install wdio-spec-reporter --save
npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! Linux 4.2.0-35-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "wdio-spec-reporter" "--save"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/wdio-spec-reporter
npm ERR! 404 
npm ERR! 404  'wdio-spec-reporter' is not in the npm registry.
`

**Comment by openam** [comment]
It doesn't look like this reporter works even if I install it directly, e.g. `npm install webdriverio/wdio-spec-reporter`.

**Comment by christian-bromann** [comment]
This reporter doesn't work yet. Please use the dot reporter in the meantime. It will output the same error report as the spec reporter.

**Comment by kashesandr** [comment]
Please add the nodejs spec reporter to for npm

**Comment by christian-bromann** [comment]
> Please add the nodejs spec reporter for npm

@kashesandr what do you mean?

**Comment by kashesandr** [comment]
@christian-bromann
I mean I agree with the topic starter and it'll be useful to have the module in npm :)
I'm currently setting up the integration testing and faced with the problem - can't use the spec reporter easily... 
Sorry if confused you.

**Comment by christian-bromann** [comment]
Like I said, use the dot reporter in the meantime, it shows you the same error output as the dot reporter

**Comment by bichotll** [comment]
What is it doing on the website then?
http://webdriver.io/guide/testrunner/reporters.html

You should comment on the readme that it's not ready ;)

**Comment by christian-bromann** [comment]
@bichotll apparently this is an outdated page (see http://webdriver.io/guide/reporters/dot.html) .. our s3 sync mechanism doesn't seem to clear deleted files

**Comment by stsvilik** [comment]
@christian-bromann what prevents this repo from being published to NPM? Something in particular? It seemed to be working fine locally. Some of us could take a look at it in the free time (to fix whatever is broken).

**Comment by christian-bromann** [comment]
I don't think it is working if you run it with multiple sessions at the same time, I see some stuff left to do:
- print the logs of a test in one step once the test has finished
- maybe have a similar preemble like protractor: `[firefox 45.0 Windows 8.1 #1o]` to identify the session

If you guys could manage to implement that it would be awesome 👍

**Comment by stsvilik** [comment]
@christian-bromann we could definitely take a look, but to be fare this could be an iterative process. First you release what works and then add features as you go along. If you wait until it is perfect you may never get it out :)

**Comment by bichotll** [comment]
Just a comment, in that case I recommend to leave a clear note on the
Readme.md.

**Comment by monolithed** [comment]
> This reporter doesn't work yet. Please use the dot reporter in the meantime. It will output the same error report as the spec reporter.

There's no `describe` section:

![img-2016-06-23-01-55-27](https://cloud.githubusercontent.com/assets/803674/16286523/a9e14db2-38e5-11e6-84ef-5ae5f207c9e5.png)
![img-2016-06-23-01-54-40](https://cloud.githubusercontent.com/assets/803674/16286524/a9e30dbe-38e5-11e6-9c39-fe5debfa882e.png)

**Comment by christian-bromann** [comment]
@monolithed what do you mean by that? Like I said this reporter isn't ready yet. It is not published on the website and has no readme. Should clearly indicate that this project is work in progress.

**Comment by monolithed** [comment]
@christian-bromann, I mean that there's no `describe` section in dot reporter, nothing else :)

**Comment by dheerajbhaskar** [comment]
@christian-bromann if dot reporter is ready for npm, then can I just fork that and add the `describe` section to that, or is there any other difference with spec reporter?

**Comment by christian-bromann** [comment]
@monolithed please file an issue in the wdio-dot-reporter project then

@dheerajbhaskar sure you can

**Comment by monolithed** [comment]
https://github.com/webdriverio/wdio-dot-reporter/issues/1

**Comment by christian-bromann** [comment]
Just released a beta version `v0.0.1`
