### ISSUE TITLE
List things needed to push this to npm

### ISSUE THREAD

**Issue by dheerajbhaskar** [webdriverio/wdio-spec-reporter#4]
Per #3 @christian-bromann mentioned the two following things needed to push this to npm.

- [ ] print the logs of a test in one step once the test has finished
- [ ] maybe have a similar preemble like protractor: [firefox 45.0 Windows 8.1 #1o] to identify the session

Is there anything else or just this? 

I'm willing to pitch in a little of my dev time. We should split identified items into different issues and put them in a milestone and release as soon as they're closed. We can iterate this for future updates

**Comment by christian-bromann** [comment]
I started working on it, it will be something similar like protractor has

**Comment by timbru31** [comment]
The work so far looks god @christian-bromann, I was able to use the runner successfully 👍

**Comment by christian-bromann** [comment]
Just released a beta version `v0.0.1`
