### ISSUE TITLE
Console output in jenkins is not correct

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/wdio-spec-reporter#66]
_From @andrea-raabe on November 23, 2017 13:57_

## The problem

The console output with the spec reporter in jenkins is not correct.

The checkmark (and special signs) displayed not correct: **[32m✓[0m**

## Environment

* WebdriverIO version: 4.9.9
* Node.js version:
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

`
[chrome #0-1] Session ID: cc6195047bb0ee11656db99c50c73114

[chrome #0-1] Spec: /home/jenkins/workspace/Frontend/PortalDev-03-EndToEndChrome/tests/portal/angebotsalarm.js
[chrome #0-1] Running: chrome
[chrome #0-1]
[chrome #0-1]   Angebotsalarm
[chrome #0-1]       [32m✓[0m Bei Klick ...
[chrome #0-1]       [32m✓[0m Der Dialog ...
[chrome #0-1]
[chrome #0-1]
[chrome #0-1] [32m2[0m [32mpassing[0m (21s)
[chrome #0-1]
`

_Copied from original issue: webdriverio/webdriverio#2469_

**Comment by sherlock1982** [comment]
Not fullly fixed. In summary I still see it:


```
[32m205 passing[0m[90m (1782.90s)[0m
[36m18 skipped[0m
[31m2 failing[0m

[0m1) People test navigate each group:
[0m[31melement ("span=036") still not existing after 10000ms[0m[93m
running chrome on linux
running firefox on linux[0m[90m
Error: element ("span=036") still not existing after 10000ms
    at Context.it (test/webclient/people/people.spec.ts:14:17)
    at Promise.F (node_modules/wdio-sync/node_modules/core-js/library/modules/_export.js:35:28)
    at elements("span=036") - isExisting.js:46:17
    at isExisting("span=036") - waitForExist.js:67:22
[0m
```

**Comment by andrea-raabe** [comment]
the output is still wrong

**Comment by christian-bromann** [comment]
@sherlock1982 the other part will be tackled by webdriverio/webdriverio#878

**Comment by andrea-raabe** [comment]
But the issue #878 is very old. 
The output is wrong since the version 4.9.6 (10.11.17).

[chrome #0-2]   /api/ URL Generator
[chrome #0-2]       [32m✓[0m /api/url/brochure/{id}
[chrome #0-2]       [32m✓[0m /api/url/brochure/{id}#page
[chrome #0-2]       [32m✓[0m /api/url/product/{id}
[chrome #0-2]       [32m✓[0m /api/url/store/{id}
[chrome #0-2]
[chrome #0-2]
[chrome #0-2] [32m4[0m [32mpassing[0m (11s)

**Comment by sherlock1982** [comment]
@andrea-raabe please check wdio-spec-reporter version 0.1.3. It was just published and this issue is fixed there. Except the footer mentioned here.

**Comment by andrea-raabe** [comment]
thx, now it works
