### ISSUE TITLE
Some test results are not printed

### ISSUE THREAD

**Issue by timbru31** [webdriverio/wdio-spec-reporter#8]
I'm not sure if this is an acutal issue with wdio-spec-reporter or the runner. Sometimes no test results are printed , as it seems that no `runner:end` event was received. The dort reporter works though, since it prints the results on `test:end`

See attached screenshot. I'm still looking on how to reproduce this issue.

![image](https://cloud.githubusercontent.com/assets/838003/16879251/134341b2-4ab0-11e6-82a7-b12025248cff.png)
## Used versions

webdriverio: 4.2.1
wdio-cucumber-framework: 0.2.1
wdio-spec-reporter: 0.0.2
node: 4.4.7

**Comment by christian-bromann** [comment]
> it seems that no runner:end event was received

Yeah looks like it. Not quite sure why tho. Can you create a reproducible example?

**Comment by timbru31** [comment]
Once I have a working examples to reproduce the issue, I'll let you know

**Comment by christian-bromann** [comment]
This is fixed in the framework adapters and will be released soon

**Comment by timbru31** [comment]
Glad to hear you could solve it - sorry for not providing a reproducible example.
